# .yamllint.workflows.yaml
extends: default

rules:
  line-length:
    max: 180
    level: warning
  truthy:
    level: warning        # bisa diubah ke 'disable' kalau perlu lebih longgar
  indentation:
    indent-sequences: consistent
    check-multi-line-strings: false
  trailing-spaces: enable
  document-start: disable
