# .yamllint.workflows.yaml
extends: default

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    level: warning
  indentation:
    indent-sequences: consistent
    check-multi-line-strings: false
  trailing-spaces: enable
  document-start: disable
