# .yamllint.workflows.yaml
extends: default

rules:
  line-length:
    max: 140
    level: warning
  truthy:
    level: warning
  indentation:
    indent-sequences: consistent
  trailing-spaces: enable
  document-start: disable
