# .github/branch-protection.yml
# Declarative branch protection rules for GitHub

name: branch-protection

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "branch protection check ok"
