# GitHub Sponsors (username GitHub Anda)
github: EndiHariadi43

# Patreon
patreon: EndiHariadi43

# Platform lain
#ko_fi: yourKoFiID
#open_collective: yourOpenCollectiveID
#liberapay: yourLiberapayID

# Custom links (bisa lebih dari satu)
custom: ["https://saweria.co/EndiHariadi43", "https://trakteer.id/EndiHariadi43"]