# GitHub Sponsors
github: EndiHariadi43

# Patreon
patreon: EndiHariadi43

# platform lain
#ko_fi: yourKoFiID
#open_collective: yourOpenCollectiveID
#liberapay: yourLiberapayID
#custom: ["https://saweria.co/yourSaweriaID", "https://trakteer.id/yourTrakteerID"]
