# Konfigurasi yamllint KHUSUS untuk .github/workflows
extends: default

rules:
  line-length:
    max: 160        # sedikit lebih longgar untuk baris command yang panjang
    level: warning
  truthy:
    level: warning
  indentation:
    indent-sequences: consistent
  trailing-spaces: enable
  document-start: disable

# Jangan ignore apa pun di sini — kita memang ingin melint file workflow
ignore: |
