# Konfigurasi yamllint untuk SELURUH repo
extends: default

rules:
  line-length:
    max: 140
    level: warning
  truthy:
    level: warning
  indentation:
    indent-sequences: consistent
    check-multi-line-strings: false
  trailing-spaces: enable
  document-start: disable

# Folder/file yang diabaikan pada lint umum
ignore: |
  .git/
  node_modules/
  dist/
  build/
  **/*.md
  .github/workflows/*      # <- workflows di-skip di lint umum, dilint terpisah dengan config override
