# .yamllint.workflows.yaml
extends: default

rules:
  document-start: disable
  line-length:
    max: 200
    level: warning
  truthy:
    level: warning
  indentation:
    indent-sequences: consistent
    check-multi-line-strings: false
  trailing-spaces:
    level: warning
  empty-lines:
    level: warning

ignore: |
  .git/
  node_modules/
  dist/
  build/
  **/*.md
  .github/workflows/**        # ← workflows diabaikan pada lint “repo only”
