blank_issues_enabled: false

contact_links:
  - name: 🔒 Security reports
    url: mailto:endi.linux.mint@gmail.com
    about: Please report security vulnerabilities privately via email. Do not open a public issue.
