name: BhinnekaBot (TON Premium)

on:
  schedule:
    #- cron: "0 * * * *"           # jalan tiap jam (UTC)
    - cron: "0 */6 * * *"   # tiap 6 jam
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: bhinnekabot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # run pertama: artifact bisa belum ada → abaikan error
      - name: Restore DB artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: bhinneka-db
          path: .
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show files (debug)
        run: ls -al

      # sanity check: token valid?
      - name: Check Telegram token (getMe)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsS "https://api.telegram.org/bot${BOT_TOKEN}/getMe" | tee getme.json

      # pastikan polling (hapus webhook kalau ada)
      - name: Ensure polling (delete webhook)
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          set -euo pipefail
          curl -fsS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/deleteWebhook" | tee delwh.json

      # pastikan DB ada agar upload sukses di run pertama
      - name: Ensure DB file exists (first run safety)
        run: |
          if [ ! -f bhinneka.db ]; then
            python -c "import sqlite3; con=sqlite3.connect('bhinneka.db'); con.execute('CREATE TABLE IF NOT EXISTS _init(id INTEGER)'); con.commit(); con.close()"
          fi
          ls -l bhinneka.db

      # JALANKAN BOT — TANPA "|| true"!
      - name: Run bot (short test 2m)
  env:
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    TON_DEST_ADDRESS: ${{ secrets.TON_DEST_ADDRESS }}
    TONCENTER_API: ${{ secrets.TONCENTER_API }}
    TONCENTER_API_KEY: ${{ secrets.TONCENTER_API_KEY }}
    PREMIUM_PRICE_TON: ${{ secrets.PREMIUM_PRICE_TON }}
    PREMIUM_DAYS: ${{ secrets.PREMIUM_DAYS }}
    PYTHONUNBUFFERED: "1"
  run: |
    set -euo pipefail
    echo "Starting BhinnekaBot..."

    # Jangan hentikan step saat timeout (exit 124)
    set +e
    timeout 2m bash -o pipefail -c 'python -u bhinnekabot.py 2>&1 | tee bhinnekabot.log'
    ec=$?
    set -e

    echo "exit code: $ec"
    if [ "$ec" -eq 124 ]; then
      echo "Timeout reached — treating as success."
      exit 0
    fi
    exit "$ec"

      # upload DB + LOG setiap kali run (berhasil/gagal)
      - name: Upload artifacts (DB + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bhinneka-run
          path: |
            bhinneka.db
            bhinnekabot.log
            getme.json
            delwh.json
          retention-days: 14

      # simpan DB dengan nama tetap (untuk dipakai run berikutnya)
      - name: Upload DB artifact (compat)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bhinneka-db
          path: bhinneka.db
          retention-days: 14
