name: Branch Policy Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      # Lint SEMUA YAML di repo KECUALI workflows
      - name: Run yamllint (repo only, exclude workflows)
        run: |
          set -euo pipefail
          files="$(git ls-files '*.yml' '*.yaml' | grep -v '^\.github/workflows/')" || true
          if [ -n "$files" ]; then
            echo "$files" | xargs yamllint -c .yamllint.yaml
          else
            echo "No non-workflow YAML files to lint."
          fi

      # Lint KHUSUS workflows dengan aturan lebih longgar
      - name: Run yamllint (workflows only, relaxed rules)
        run: |
          set -euo pipefail
          if ls .github/workflows/*.yml .github/workflows/*.yaml >/dev/null 2>&1; then
            yamllint -c .yamllint.workflows.yaml .github/workflows
          else
            echo "No workflow YAML files found."
          fi

      - name: Branch policy marker
        run: echo "✅ branch protection check ok"
