name: Branch Policy Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:                  # <--- ubah dari "check" jadi "yamllint"
    name: yamllint           # <--- ini yang akan muncul di Required status checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install --upgrade pip yamllint

      - name: Run yamllint
        run: yamllint -s .

      - name: Branch policy marker
        run: echo "✅ branch protection check ok"
