name: Branch Policy Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:                # <- Nama job ini akan tampil sebagai required check: "yamllint"
    name: yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install --upgrade pip yamllint

      # Lint seluruh repo memakai konfigurasi root (.yamllint.yaml)
      - name: Run yamllint (repo)
        run: yamllint -s .

      # Lint khusus workflow memakai konfigurasi override agar folder ini TIDAK di-ignore
      - name: Run yamllint (workflows only)
        run: yamllint -s -c .github/.yamllint.workflows.yaml .github/workflows

      - name: Branch policy marker
        run: echo "✅ branch protection checks passed"
