name: branch-protection

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "Repo    : $GITHUB_REPOSITORY"
          echo "Ref     : $GITHUB_REF"
          echo "Actor   : $GITHUB_ACTOR"
          echo "Event   : $GITHUB_EVENT_NAME"

      - name: Checkout repo
        uses: actions/checkout@v4

      # Validasi YAML supaya PR tidak bisa merge kalau YAML salah
      - name: Validate YAML files
        run: |
          pip install yamllint
          yamllint -d "{extends: default, rules: {line-length: disable}}" .
