name: Branch Policy Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install --upgrade pip yamllint

      # 1) Lint repo utama, exclude workflows
      - name: Run yamllint (repo only)
        run: yamllint -s -c .yamllint.yaml -- . ':!.github/workflows'

      # 2) Lint khusus workflows dengan aturan berbeda
      - name: Run yamllint (workflows only, relaxed rules)
        run: yamllint -s -c .yamllint.workflows.yaml .github/workflows

      - name: Branch policy marker
        run: echo "✅ branch protection check ok"
